version: '3.5'

services:
  offline_project_db:
    container_name: offline_project_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    image: postgres:15.4-alpine3.18
