version: '3.8'

services:
  offline_project_db:
    container_name: offline_project_db
    image: postgres:15.4
    environment:
      POSTGRES_DB:  ${ARG1}
      POSTGRES_USER: ${ARG2}
      POSTGRES_PASSWORD: ${ARG3}
    networks:
        - localnet
    volumes:
      - ./db:/home/offline_project_db

  offline_project_db_migrate_up:
    image: migrate/migrate:4
    command: ["-path", "/migrations", "-database", "postgres://postgres:123@offline_project_db:5432/offline_project_db?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet
    depends_on:
      - offline_project_db

networks:
  localnet:
    name: localnet
    driver: bridge
