version: '3.8'

services:
  offline_project_db:
    container_name: 
      offline_project_db
    image: 
      postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: offline_project_db
    networks:
      - localnet
    volumes:
      - ./db:/home/offline_project_db

  offline_project_backend:
    container_name:
      offline_project_backend
    image: 
      golang:1.21
    environment:
      POSTGRES_CONNECTION_STRING: "postgres://postgres:123@offline_project_db:5432/offline_project_db?sslmode=disable"
    networks:
      - localnet
    ports:
      - "3000:3000"
    volumes:
      - .:/home/offline_project
    command:
      [
        "mkdir", "tmp", "&&",
        "cd", "tmp", "&&",
        "go", "get", "github.com/kyleconroy/sqlc/cmd/sqlc", "&&",
        "go", "install", "github.com/kyleconroy/sqlc/cmd/sqlc"
      ]

  offline_project_db_migrate_up:
    image: 
      migrate/migrate:4
    command: 
      ["-path", "/migrations", "-database", "postgres://postgres:123@offline_project_db:5432/offline_project_db?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet
    depends_on:
      - offline_project_db

  offline_project_db_migrate_down:
    image: migrate/migrate:4
    #                                              "postgres://your_username:your_password@your_db_docker_compose_service:5432/your_database?sslmode=disable"
    command: ["-path", "/migrations", "-database", "postgres://postgres:123@offline_project_db:5432/offline_project_db?sslmode=disable", "down", "-all"]
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet
    depends_on:
      - offline_project_db

  offline_project_db_migration_tool:
    # To check current version: docker-compose run offline_project_db_migration_tool -path /migrations -database "postgres://postgres:123@offline_project_db:5432/offline_project_db?sslmode=disable" version
    # To check current version: docker-compose run offline_project_db_migration_tool -path /migrations -database "postgres://postgres:123@offline_project_db:5432/offline_project_db?sslmode=disable" force <desired version>
    # Then run service: offline_project_db_migrate_up
    image: 
      migrate/migrate:4
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet
    depends_on:
      - offline_project_db

networks:
  localnet:
    name: 
      localnet
    driver: 
      bridge
