version: '3.8'

services:
  offline_project_db:
    container_name: offline_project_db
    image: postgres:15.4
    environment:
      POSTGRES_DB: $ARG1
      POSTGRES_USER: $ARG2
      POSTGRES_PASSWORD: $ARG3
    networks:
        - localnet
    volumes:
      - ./db:/home/offline_project_db

  offline_project_backend:
      container_name: offline_project_backend
      image: golang:1.21
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB_NAME: offline_project_db
        POSTGRES_PORT: 5432
        DOCKER_NETWORK_NAME: localnet
        DOCKER_DB_CONTAINER_NAME: offline_project_db
      networks:
        - localnet
      volumes:
        - ./backend:/home/offline_project_backend
      depends_on:
        - offline_project_db

  offline_project_db_migration_tool:
    image: migrate/migrate:4
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet
    depends_on:
      - offline_project_db

networks:
  localnet:
    name: localnet
    driver: bridge