version: '3.8'

networks:
  localnet:
    name: 
      localnet
    driver: 
      bridge
      
services:
  service_db_handler:
    containter_name:
      service_db_handler
    networks:
      - localnet
    build:
      context: 
        ./service_db_handler
      dockerfile: 
        ./service_db_handler/Dockerfile
