version: '3.8'

services:
  offline_project_db:
    container_name: offline_project_db
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: offline_project_db
    ports:
      - '5432:5432'
    networks:
        - localnet
    volumes:
      - ./db:/home/offline_project_db

  offline_project_backend:
      container_name: offline_project_backend
      image: golang:1.21
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB_NAME: offline_project_db
        POSTGRES_PORT: 5432
        DOCKER_NETWORK_NAME: localnet
        DOCKER_DB_CONTAINER_NAME: offline_project_db
      ports:
        - '3000:3000'
      networks:
        - localnet
      volumes:
        - ./backend:/home/offline_project_backend

networks:
  localnet:
    name: localnet
    driver: bridge
