version: '3'

networks:
  localnet:
    driver: bridge

volumes:
  offline_project_data:

services:
  proxy:
    container_name: 
      proxy
    image:
      nginx:1.23.3-alpine
    volumes:
      - proxy/certs/*:/etc/nginx/ssl/localhost/
      - proxy/config/localhost.conf /etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - keycloak
    networks:
      - localnet

  keycloak:
    container_name: 
      keycloak
    image: 
      keycloak/keycloak
    command: 
      start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public

      KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: https://localhost:8443
      KC_HOSTNAME_URL: https://localhost:8443

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    networks:
      - localnet

  keycloak_postgres:
    image: 
      postgres:14.2
    command: 
      postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_nginx_demo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: 
        "exit 0"
    ports:
      - "5436:5432"
    networks:
      - localnet
