version: '3'
name: offline_project

volumes:
  keycloak_postgres_volume:

networks:
  local_network:
    driver: bridge

services:
  gateway:
    container_name: gateway
    image: nginx:1.23.3-alpine
    volumes:
      - ./gateway/gateway.conf:/etc/nginx/nginx.conf
    networks:
      local_network:         
        aliases:
          - gateway.localtest.me
    ports:
      - "80:80"

  chats_service:
    container_name: chats_service
    build:
      context: .
      dockerfile: chats_service/Dockerfile
    environment:
      - ENTRYPOINT_ADDRESS=
      - ENTRYPOINT_PORT=80
    networks:
      - local_network

