version: '3'
name: offline_project

networks:
  gateway_network:
    driver: bridge

services:
  gateway:
    container_name: gateway
    image: nginx:1.23.3-alpine
    volumes:
      - ./gateway/gateway.conf:/etc/nginx/nginx.conf
    networks:
      gateway_network:         
        aliases:
          - gateway.localtest.me
    ports:
      - "80:80"
    depends_on:
      - service_messenger

  service_messenger:
    container_name: service_messenger
    build:
      context: .
      dockerfile: service_messenger/Dockerfile
    networks:
      - gateway_network