version: '3'
name: offline_project

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

services:
  gateway:
    container_name: gateway
    image: nginx:1.23.3-alpine
    volumes:
      - ./gateway/gateway.conf:/etc/nginx/nginx.conf
    networks:
      - frontend_network
      - backend_network
    ports:
      - "80:80"
    depends_on:
      - service_messenger

  service_messenger:
    container_name: service_messenger
    build:
      context: .
      dockerfile: service_messenger/Dockerfile
    networks:
      - backend_network