version: '3'
name: offline_project

networks:
  chats_network:
    driver: bridge

services:
  gateway:
    container_name:
      gateway
    image:
      nginx:1.23.3-alpine
    volumes:
      - ./gateway/gateway.conf:/etc/nginx/nginx.conf
    networks:
      chats_network:         
        aliases:
          - gateway.localtest.me
    ports:
      - "8080:80"

  chats_service:
    container_name:
      chats_service
    image: 
      golang:1.22
    volumes:
      - ./chats_service:/home/offline_project/chats
    networks:
      - chats_network
