version: '2.4'

services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #     - ./proxy/logs:/var/log/nginx
  #   ports:
  #     - 80:80

  go-http-server:
    build: go_module/
    ports:
      - "8080:8080"