// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	Login       string
	Password    string
	Mail        string
	Phone       string
	FirstName   string
	SecondName  string
	DateOfBirth time.Time
	CreatedAt   time.Time
}
