// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID    uuid.UUID
	Title string
}

type ChatComment struct {
	ID        uuid.UUID
	ChatID    uuid.UUID
	AuthorID  uuid.UUID
	CreatedAt time.Time
	EditedAt  time.Time
	Text      string
}

type User struct {
	ID          uuid.UUID
	Login       string
	Password    string
	Mail        string
	Phone       string
	FirstName   string
	SecondName  string
	DateOfBirth time.Time
	CreatedAt   time.Time
}
